import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  sidebarsworkbooks: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'doc',
        id: 'getting-started/overview',
      },
      items: ['getting-started/licensing','getting-started/deploying'],
    },
    {
      type: 'category',
      label: 'Code Snippets',
      link: {
        type: 'doc',
        id: 'code-snippets/overview',
      },
      items: [
        {
          type: 'category',
          label: 'Annotations',       // Nombre de la subcategoría
          link: {
            type: 'generated-index',
            description: 'Demonstrates how to add a Chart to a Document',            
          },
          items: [
            'code-snippets/annotation/adding-note',
            'code-snippets/annotation/adding-comment',
            'code-snippets/annotation/changing-note-formatting',
            'code-snippets/annotation/identifying-notes-comments',
          ],
        },
        {
          type: 'category',
          label: 'Cell',       // Nombre de la subcategoría
          link: {
            type: 'generated-index',
            description: 'Demonstrates how to handle HTML, objects, text replacing and converting to pdf',  
          },
          items: [            
            'code-snippets/cell/cell-with-multiple-fonts',
            'code-snippets/cell/delete-cell-range',
            'code-snippets/cell/format-part-of-text',        
            'code-snippets/cell/insert-cell-range',
            'code-snippets/cell/merge-cells',     
            'code-snippets/cell/replace-content',     
            'code-snippets/cell/set-cell-value-type',     
            'code-snippets/cell/set-formulas',     
          ],
        },
        {
          type: 'category',
          label: 'Column',       // Nombre de la subcategoría
          link: {
            type: 'generated-index',
            description: 'Working with pictures in documents',  
          },
          items: [
            'code-snippets/column/clear-column-contents',
            'code-snippets/column/column-cell-access',
            'code-snippets/column/customize-columns',
            'code-snippets/column/hide-unhide-columns',
          ],
        },
        {
          type: 'category',
          label: 'Import Data',       // Nombre de la subcategoría
          link: {
            type: 'generated-index',
            description: 'Shapes in documents, as text wrapping and TextBoxes',  
          },
          items: [
            'code-snippets/import-data/import-arrays',
            'code-snippets/import-data/import-collections',
            'code-snippets/import-data/import-csv',
            'code-snippets/import-data/import-datatables',
          ],
        },
        {
          type: 'category',
          label: 'Picture',       // Nombre de la subcategoría
          link: {
            type: 'generated-index',
            description: 'Navigate yourself thorough the content',  
          },
          items: [
            'code-snippets/picture/add-picture',
            'code-snippets/picture/offset-picture',
            'code-snippets/picture/shrink-picture-with-offset',
          ],
        },
        {
          type: 'category',
          label: 'Protection',       // Nombre de la subcategoría
          link: {
            type: 'generated-index',
            description: 'Tables, cells, rows and more in a document',  
          },
          items: [
            'code-snippets/protection/add-worksheet-protection',
            'code-snippets/protection/add-worksheet-password',
            'code-snippets/protection/add-worksheet-allow-actions',
            'code-snippets/protection/remove-worksheet-protection',
            'code-snippets/protection/lock-specific-cell',
            'code-snippets/protection/unlock-specific-cell',
          ],
        },
        {
          type: 'category',
          label: 'Row',       // Nombre de la subcategoría
          link: {
            type: 'generated-index',
            description: 'And we have more...',  
          },
          items: [
            'code-snippets/row/row-cell-access',
            'code-snippets/row/customize-rows',
            'code-snippets/row/hide-unhide-rows',
          ],
        },{
          type: 'category',
          label: 'Sheet View',       // Nombre de la subcategoría
          link: {
            type: 'generated-index',
            description: 'And we have more...',  
          },
          items: [
            'code-snippets/sheetview/set-active-cell',
            'code-snippets/sheetview/set-zoom-view-type',
            'code-snippets/sheetview/freeze-rows-columns',        
            'code-snippets/sheetview/split-rows-columns', 
          ],
        },{
          type: 'category',
          label: 'Style',       // Nombre de la subcategoría
          link: {
            type: 'generated-index',
            description: 'And we have more...',  
          },
          items: [
            'code-snippets/style/set-alignment',
            'code-snippets/style/set-borders',
            'code-snippets/style/text-direction-orientation',        
             'code-snippets/style/modify-theme', 
          ],
        },{
          type: 'category',
          label: 'Table',       // Nombre de la subcategoría
          link: {
            type: 'generated-index',
            description: 'And we have more...',  
          },
          items: [
            'code-snippets/table/add-formatted-table',
            'code-snippets/table/remove-tables',
          ],
        },{
          type: 'category',
          label: 'Workbooks',       // Nombre de la subcategoría
          link: {
            type: 'generated-index',
            description: 'And we have more...',  
          },
          items: [
            'code-snippets/workbook/create-workbook',
            'code-snippets/workbook/calculate-workbook-formulas',
            'code-snippets/workbook/load-workbook-from-filename',        
             'code-snippets/workbook/load-workbook-with-stream', 
          ],
        },{
          type: 'category',
          label: 'Worksheet',       // Nombre de la subcategoría
          link: {
            type: 'generated-index',
            description: 'And we have more...',  
          },
          items: [
            'code-snippets/worksheet/add-remove-hide-worksheet',
            'code-snippets/worksheet/cell-row-column-access',
            'code-snippets/worksheet/calculate-worksheet-formulas',        
             'code-snippets/worksheet/insert-delete-rows',                        
             'code-snippets/worksheet/insert-delete-columns',
          ],
        },
        ],
    },
  ],
};

export default sidebars;