import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  sidebarftp: [
    'intro',
    'sftp_intro',
    {
      type: 'category',
      label: 'Installation Instructions',
      link: {
        type: 'doc',
        id: 'installation-instructions/overview',
      },
      items: ['installation-instructions/how-45-trial-works','installation-instructions/how-to-license-component','installation-instructions/installation-csharp','installation-instructions/installation-vb','installation-instructions/installation-net',],
    },
    {
      type: 'category',
      label: 'Basic Concepts',
      link: {
        type: 'doc',
        id: 'basic-concepts/getting-started',
      },
      items: [
        'basic-concepts/net-frm-4-45',
        {
          type: 'category',
          label: 'Xceed\'\s File System Core',
          link: {
            type: 'doc',
            id: 'basic-concepts/xceed-filesystem-core/overview',
          },
          items: [
            'basic-concepts/xceed-filesystem-core/case-sensitivity',
            'basic-concepts/xceed-filesystem-core/listing-content-folder',
            'basic-concepts/xceed-filesystem-core/copy-items-folder',
            'basic-concepts/xceed-filesystem-core/remove-item-folder',
            'basic-concepts/xceed-filesystem-core/access-file-long-name',
            ],
        },
        {
          type: 'category',
          label: 'FTP Capabilities',
          link: {
            type: 'doc',
            id: 'basic-concepts/ftp-capabilities/overview',
          },
          items: [
            'basic-concepts/ftp-capabilities/the-ftp-protocol',
            {
              type: 'category',
              label: 'FTP Client interface',
              link: {
                type: 'generated-index',
                description: 'This section contains topics relating to the FtpClient interface.',     
              },
              items: [
                'basic-concepts/ftp-capabilities/ftp-client-interface/winform-apps-threading',
                'basic-concepts/ftp-capabilities/ftp-client-interface/ftp-client-properties',
                'basic-concepts/ftp-capabilities/ftp-client-interface/ftp-client-methods',
                'basic-concepts/ftp-capabilities/ftp-client-interface/ftp-client-events',
                ],
            },
            {
              type: 'category',
              label: 'FTP glossary',
              link: {
                type: 'generated-index',
                description: 'This section contains a glossary of terms relating to FTP.',     
              },
              items: [
                'basic-concepts/ftp-capabilities/ftp-glossary/control-connection',
                'basic-concepts/ftp-capabilities/ftp-glossary/data-port',
                'basic-concepts/ftp-capabilities/ftp-glossary/data-connection',
                'basic-concepts/ftp-capabilities/ftp-glossary/ftp-commands',
                'basic-concepts/ftp-capabilities/ftp-glossary/ftp-replies',
                'basic-concepts/ftp-capabilities/ftp-glossary/http-proxy-server',
                'basic-concepts/ftp-capabilities/ftp-glossary/ssl-tls',
                'basic-concepts/ftp-capabilities/ftp-glossary/type',
                ],
            },
            {
              type: 'category',
              label: 'FTP using the FileSystem interface',
              link: {
                type: 'generated-index',
                description: 'This section of the manual presents some basic FTP operations using the FileSystem interface.',     
              },
              items: [
                'basic-concepts/ftp-capabilities/ftp-using-filesystem-interface/copy-item-from-ftp',
                'basic-concepts/ftp-capabilities/ftp-using-filesystem-interface/copy-item-to-ftp',
                'basic-concepts/ftp-capabilities/ftp-using-filesystem-interface/list-all-item-on-ftp',
                'basic-concepts/ftp-capabilities/ftp-using-filesystem-interface/display-content-of-file',
                ],
            },
            'basic-concepts/ftp-capabilities/using-fxp-protocol',
            'basic-concepts/ftp-capabilities/secure-ftp',
            ],
        },
        {
          type: 'category',
          label: 'SFTP Capabilities',
          link: {
            type: 'doc',
            id: 'basic-concepts/sftp-capabilities/overview',
          },
          items: [
            'basic-concepts/sftp-capabilities/proxy-support',
            'basic-concepts/sftp-capabilities/public-key-auth',
            'basic-concepts/sftp-capabilities/keyboard-interactive-auth',
            'basic-concepts/sftp-capabilities/key-exch-algorithm-negotiation',
            'basic-concepts/sftp-capabilities/handling-file-sharing-issues',
            'basic-concepts/sftp-capabilities/remote-command-exec',            
            ],
        },
        {
          type: 'category',
          label: 'Filters',
          link: {
            type: 'doc',
            id: 'basic-concepts/filters/overview',
          },
          items: [
            'basic-concepts/filters/and-filter-class',         
            'basic-concepts/filters/attribute-filter-class',         
            'basic-concepts/filters/datetime-filter-class',         
            'basic-concepts/filters/namefilter-class',         
            'basic-concepts/filters/notfilter-class',         
            'basic-concepts/filters/sizefilter-class',         
            'basic-concepts/filters/orfilter-class',         
            'basic-concepts/filters/reparse-point-tags-filter-class',         
            ],
        },
        'basic-concepts/quick-ftp-class',
        ],
    },
    {
      type: 'category',
      label: 'Task Based Help',
      link: {
        type: 'doc',
        id: 'code-snippets/overview',
      },
      items: [
        'code-snippets/file-system-explorer',
        {
          type: 'category',
          label: 'Working with classes from the Xceed.FileSystem namespace',
          link: {
            type: 'generated-index',
            description: 'This section contains task-based help relating to working with the Xceed.FileSystem namespace.',    
          },
          items: [
            'code-snippets/working-with-classes-from-filesystem/file01',
            'code-snippets/working-with-classes-from-filesystem/file02',
            'code-snippets/working-with-classes-from-filesystem/file03',
            'code-snippets/working-with-classes-from-filesystem/file04',
            'code-snippets/working-with-classes-from-filesystem/file05',
            'code-snippets/working-with-classes-from-filesystem/file06',
            'code-snippets/working-with-classes-from-filesystem/file07',
            'code-snippets/working-with-classes-from-filesystem/file08',
            'code-snippets/working-with-classes-from-filesystem/file09',
            'code-snippets/working-with-classes-from-filesystem/file10',
            'code-snippets/working-with-classes-from-filesystem/file11',
            'code-snippets/working-with-classes-from-filesystem/file12',
            'code-snippets/working-with-classes-from-filesystem/file13',
            'code-snippets/working-with-classes-from-filesystem/file14',
            ],
        },
        {
          type: 'category',
          label: 'Working with the FtpClient interface',
          link: {
            type: 'generated-index',
            description: 'This section contains task-based help relating to working with the FtpClient interface.',    
          },
          items: [
            'code-snippets/working-with-ftpclient-interface/file01',
            'code-snippets/working-with-ftpclient-interface/file02',
            'code-snippets/working-with-ftpclient-interface/file03',
            'code-snippets/working-with-ftpclient-interface/file04',
            'code-snippets/working-with-ftpclient-interface/file05',
            'code-snippets/working-with-ftpclient-interface/file06',
            'code-snippets/working-with-ftpclient-interface/file07',
            'code-snippets/working-with-ftpclient-interface/file08',
            ],
        },
        {
          type: 'category',
          label: 'Working with the QuickFtp Class',
          link: {
            type: 'generated-index',
            description: 'This section contains task-based help relating to working with the QuickFtp class.',  
          },
          items: [
            'code-snippets/working-with-quickftp-class/file01',      
            'code-snippets/working-with-quickftp-class/file02',      
            'code-snippets/working-with-quickftp-class/file03',      
            'code-snippets/working-with-quickftp-class/file04',      
            ],
        },
        {
          type: 'category',
          label: 'Making secure connections',
          link: {
            type: 'generated-index',
            description: 'This section contains task-based help relating to making secure FTP connections.',  
          },
          items: [
            'code-snippets/making-secure-connections/file01',            
            'code-snippets/making-secure-connections/file02',            
            'code-snippets/making-secure-connections/file03',            
            'code-snippets/making-secure-connections/file04',            
            ],
        },
        {
          type: 'category',
          label: 'SFTP capabilities',
          link: {
            type: 'generated-index',
            description: 'This section contains task-based help relating to using SFTP.',  
          },
          items: [
            'code-snippets/sftp-capabilities/file01',            
            'code-snippets/sftp-capabilities/file02',            
            'code-snippets/sftp-capabilities/file03',            
            'code-snippets/sftp-capabilities/file04',            
            ],
        },
        'basic-concepts/quick-ftp-class',
        ],
    },
  ],
};

export default sidebars;