import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'doc',
        id: 'getting-started/overview',
      },
      items: ['getting-started/licensing','getting-started/deploying'],
    },
    {
      type: 'category',
      label: 'Code Snippets',
      link: {
        type: 'doc',
        id: 'code-snippets/overview',
      },
      items: [
        {
          type: 'category',
          label: 'Charts',       // Nombre de la subcategoría
          link: {
            type: 'generated-index',
            description: 'Demonstrates how to add a Chart to a Document',            
          },
          items: [
            'code-snippets/charts/adding-chart',
            'code-snippets/charts/modifying-chart',
          ],
        },
        {
          type: 'category',
          label: 'Documents',       // Nombre de la subcategoría
          link: {
            type: 'generated-index',
            description: 'Demonstrates how to handle HTML, objects, text replacing and converting to pdf',  
          },
          items: [            
            'code-snippets/documents/appending-to-adocument',
            'code-snippets/documents/replacing-text-with-html',
            'code-snippets/documents/replacing-text-with-objects',        
            'code-snippets/documents/replacing-text',
            'code-snippets/documents/converting-to-pdf',     
          ],
        },
        {
          type: 'category',
          label: 'Pictures',       // Nombre de la subcategoría
          link: {
            type: 'generated-index',
            description: 'Working with pictures in documents',  
          },
          items: [
            'code-snippets/pictures/adding-picture',
            'code-snippets/pictures/adding-picture-text-wrapping',
          ],
        },
        {
          type: 'category',
          label: 'Shapes',       // Nombre de la subcategoría
          link: {
            type: 'generated-index',
            description: 'Shapes in documents, as text wrapping and TextBoxes',  
          },
          items: [
            'code-snippets/shapes/adding-shapes',
            'code-snippets/shapes/adding-shapes-with-text-wrapping',
            'code-snippets/shapes/adding-textboxes',
          ],
        },
        {
          type: 'category',
          label: 'Sections',       // Nombre de la subcategoría
          link: {
            type: 'generated-index',
            description: 'Manage sections in documents',  
          },
          items: [
            'code-snippets/sections/inserting-sections',
            'code-snippets/sections/modifying-sections',
          ],
        },
        {
          type: 'category',
          label: 'Table of Contents',       // Nombre de la subcategoría
          link: {
            type: 'generated-index',
            description: 'Navigate yourself thorough the content',  
          },
          items: [
            'code-snippets/table-of-contents/inserting-table-of-content-at-beginning',
            'code-snippets/table-of-contents/inserting-table-of-content-at-end',
            'code-snippets/table-of-contents/updating-table-contents',
          ],
        },
        {
          type: 'category',
          label: 'Tables and Cells',       // Nombre de la subcategoría
          link: {
            type: 'generated-index',
            description: 'Tables, cells, rows and more in a document',  
          },
          items: [
            'code-snippets/tables-and-cells/creating-new-table-adding-to-document',
            'code-snippets/tables-and-cells/creating-table-inserting-rows',
            'code-snippets/tables-and-cells/adding-table-with-text-wrapping',
            'code-snippets/tables-and-cells/adding-rows-and-columns-to-table',
            'code-snippets/tables-and-cells/merging-cells-in-table',
          ],
        },
        {
          type: 'category',
          label: 'Others',       // Nombre de la subcategoría
          link: {
            type: 'generated-index',
            description: 'And we have more...',  
          },
          items: [
            'code-snippets/others/bookmarks',
            'code-snippets/others/headers-and-footers',
            'code-snippets/others/hyperlinks',        
             'code-snippets/others/lists',                        
             'code-snippets/others/paragraphs',
          ],
        }
        ],
    },
  ],
};

export default sidebars;
